// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Testfall 2', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Testfall 2', async function() {
    // Test name: Testfall 2
    // Step # | name | target | value
    // 1 | open | /diary.html | 
    await driver.get("http://127.0.0.1:5500/diary.html/diary.html")
    // 2 | setWindowSize | 550x692 | 
    await driver.manage().window().setRect({ width: 550, height: 692 })
    // 3 | click | css=div:nth-child(1) > button | 
    await driver.findElement(By.css("div:nth-child(1) > button")).click()
    // 4 | mouseOver | css=div:nth-child(1) > button | 
    {
      const element = await driver.findElement(By.css("div:nth-child(1) > button"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 5 | mouseOut | css=div:nth-child(1) > button | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
  })
})
