// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Testfall 3', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Testfall 3', async function() {
    // Test name: Testfall 3
    // Step # | name | target | value
    // 1 | open | http://127.0.0.1:5500/diary.html | 
    await driver.get("http://127.0.0.1:5500/diary.html")
    // 2 | setWindowSize | 550x692 | 
    await driver.manage().window().setRect({ width: 550, height: 692 })
    // 3 | click | id=new-entry-button | 
    await driver.findElement(By.id("new-entry-button")).click()
    // 4 | mouseOver | id=new-entry-button | 
    {
      const element = await driver.findElement(By.id("new-entry-button"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 5 | mouseOut | id=new-entry-button | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 6 | click | id=new-title | 
    await driver.findElement(By.id("new-title")).click()
    // 7 | type | id=new-title | dadad
    await driver.findElement(By.id("new-title")).sendKeys("dadad")
    // 8 | click | id=new-author | 
    await driver.findElement(By.id("new-author")).click()
    // 9 | type | id=new-author | adadad
    await driver.findElement(By.id("new-author")).sendKeys("adadad")
    // 10 | click | id=new-content | 
    await driver.findElement(By.id("new-content")).click()
    // 11 | type | id=new-content | adadda
    await driver.findElement(By.id("new-content")).sendKeys("adadda")
    // 12 | click | css=button:nth-child(4) | 
    await driver.findElement(By.css("button:nth-child(4)")).click()
    // 13 | mouseOver | css=button:nth-child(4) | 
    {
      const element = await driver.findElement(By.css("button:nth-child(4)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 14 | click | css=button:nth-child(3) | 
    await driver.findElement(By.css("button:nth-child(3)")).click()
    // 15 | close |  | 
    await driver.close()
  })
})
