// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Testfall 1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Testfall 1', async function() {
    // Test name: Testfall 1
    // Step # | name | target | value | comment
    // 1 | open | http://127.0.0.1:5500/index.html |  | 
    await driver.get("http://127.0.0.1:5500/index.html")
    // 2 | setWindowSize | 550x692 |  | 
    await driver.manage().window().setRect({ width: 550, height: 692 })
    // 3 | click | id=username |  | 
    await driver.findElement(By.id("username")).click()
    // 4 | type | id=username | admin | 
    await driver.findElement(By.id("username")).sendKeys("admin")
    // 5 | click | id=password |  | 
    await driver.findElement(By.id("password")).click()
    // 6 | type | id=password | password | 
    await driver.findElement(By.id("password")).sendKeys("password")
    // 7 | click | css=button |  | 
    await driver.findElement(By.css("button")).click()
  })
})
